# Dict mapping WHO vaccine names -> OWID vaccine names
VACCINES_WHO_MAPPING = {
    "Abdala": "Abdala",
    "Anhui ZL - Recombinant": "RBD-Dimer",
    "AstraZeneca - AZD1222": "Oxford/AstraZeneca",
    "AstraZeneca - Vaxzevria": "Oxford/AstraZeneca",
    "Beijing CNBG - BBIBP-CorV": "Sinopharm/Beijing",
    "Beijing CNBG - Inactivated": "Sinopharm/Beijing",
    "Bharat - Covaxin": "Covaxin",
    "CanSino - Ad5-nCOV": "CanSino",
    "Gamaleya - Sputnik V": "Sputnik V",
    "Janssen - Ad26.COV 2.5": "Johnson&Johnson",
    "Moderna - mRNA-1273": "Moderna",
    "Novavax - Covavax": "Novavax",
    "Pfizer BioNTech - Comirnaty": "Pfizer/BioNTech",
    "QazVac": "QazVac",
    "RBD-Dimer": "RBD-Dimer",
    "RIBSP - QazCovid": "QazVac",
    "SII - Covishield": "Oxford/AstraZeneca",
    "Sinopharm/HayatVax": "Sinopharm/HayatVax",
    "Sinovac - CoronaVac": "Sinovac",
    "Soberana02": "Soberana02",
    "SRCVB - EpiVacCorona": "EpiVacCorona",
    "Wuhan CNBG - Inactivated": "Sinopharm/Wuhan",
}
